# Use the README file as a reference to customize settings.

admin:
  # userテーブルの項目に、権限に関わらずカスタマイズ出来ていいカラムが無いので
  # updateのカラムは削っておく
  User: create, read, delete

editor:
  # userテーブルの項目に、権限に関わらずカスタマイズ出来ていいカラムが無いので
  # updateのカラムは削っておく
  User: read
